### ISSUE TITLE
Error while using GPU version

### ISSUE THREAD

**Issue by jakalssj3** [wasserth/TotalSegmentator#157]
Hi. I'm trying to use TotalSegmentator on a PC with NVIDIA GeForce RTX 2070 but each time the process stops at the same step:
```
Resampling...
  Resampled in 18.83s
Predicting part 1 of 5 ...
```

and I get the below error:
```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 7.78 GiB total capacity; 4.40 GiB already allocated; 68.75 MiB free; 4.43 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x7f6ff9866dc0>
AttributeError: 'DummyFile' object has no attribute 'flush'
```

The input file is in a .nii format and has a size of ~200 Mb.  But I get the same error with other files as well.
The PC runs Python 3.8.10 and has CUDA version 12.2. Any idea how to resolve this problem?

**Comment by wasserth** [comment]
Your GPU does not have enough memory for your big image.
You can try `--fast`, `--body_seg` or `--force_split`. These options reduce memory consumption.

**Comment by jakalssj3** [comment]
Thanks, this helped
