### ISSUE TITLE
installed pytorch with cpu option but giving cuda error

### ISSUE THREAD

**Issue by kmordhwaj** [wasserth/TotalSegmentator#54]
Hi @wasserth ,
I am running on ubuntu machine.
I have installed pytorch with cpu option only.
`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu`

then installed TotalSegmentator
`pip3 install TotalSegmentator`
it installed version 1.5.2 which I am able to get by running `TotalSegmentator --version`

but when trying to segmentate by putting a file ct.nii.gz `TotalSegmentator -i ct.nii.gz -o . --fast`
its giving error 

/usr/local/lib/python3.10/dist-packages/torch/cuda/amp/grad_scaler.py:118: UserWarning: torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.
  warnings.warn("torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.")
/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling'

please help!
thank you.

**Comment by kmordhwaj** [comment]
I resolved it by
1. not installing torch from pytorch.org (not relying on them as they were giving cuda conflict)
2. just run `sudo pip3 install TotalSegmentator`. It automatically taken its torch which it want to take.
3. then downgraded to TotalSegmentator==1.4 from its latest version.
4. now its running
5. I think the torch from pytorch.org and from the TotalSegmentator was giving some conflict issue.
