### ISSUE TITLE
Using --fast option runs out of memory even when regular option does not

### ISSUE THREAD

**Issue by bdzyubak** [wasserth/TotalSegmentator#62]
Thank you for making TotalSegmentator available. It looks like an amazing resource! 

While processing a dataset, I was running into CUDA out of memory issues for nii.gz files of around 150 MB. To process these, I tried to use the --fast option assuming that a smaller model would use less memory (and the README does indicate this). However, it had the opposite effect making files with size 92 MB, which process ok without the --fast, run out of memory: 

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.58 GiB (GPU 0; 23.70 GiB total capacity; 13.64 GiB already allocated; 4.23 GiB free; 18.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Exception ignored in: <totalsegmentator.libs.DummyFile object at 0x7f0e2c318d90>
AttributeError: 'DummyFile' object has no attribute 'flush'

**Comment by denbonte** [comment]
Hey @bdzyubak!

As a fellow TotalSegmentator user, I believe this happened to me once while playing with the tool.

Are you sure other runs/other data did not clutter your GPU VRAM? As far as I can remember, that solved the problem for me. Besides that, I ran TotalSegmentator hundreds of times and didn't run into any issues (using even bigger `.nii.gz` volumes).
